name: CWTraining
main: EnderDirt\CWTraining
version: 1.0.0
api: 3.0.0-ALPHA11
author: EnderDirt
commands:
  ClanWars:
    description: ClanWars Command
    aliases: [cw]
  Start:
    description: Start Command
    aliases: [start]