name: UHCMeetup
main: EnderDirt\UHCMeetup
version: 1.0.1
api: 3.0.0-ALPHA12
author: EnderDirt
commands:
  UHCMeetup:
    description: UHCMeetup Command
    aliases: [uhc]
  Start:
    description: Start Command
    aliases: [start]
  Stats:
    description: Stats Command
    aliases: [stats]