name: eGroups
main: EnderDirt\Main
version: 1.0.0
api: 3.0.0-ALPHA12
author: EnderDirt
commands:
  Group:
    description: Group Command
    aliases: [g]
  VIP:
    description: VIP Command
    aliases: [vip]