name: Cores
main: EnderDirt\Cores
version: 1.0.0
api: 3.0.0-ALPHA11
author: EnderDirt
commands:
  Cores:
    description: Cores Command
    aliases: [cores]
  Start:
    description: Start Command
    aliases: [start]