name: BowFight
main: EnderDirt\BowFight
version: 1.0.0
api: 3.0.0-ALPHA12
author: EnderDirt
commands:
  BowFight:
    description: BowFight Command
    aliases: [bf]
  Start:
    description: Start Command
    aliases: [start]