ingame: false
items:
  1:
    id: 298
    meta: 0
    amount: 1
  2:
    id: 299
    meta: 0
    amount: 1
  3:
    id: 300
    meta: 0
    amount: 1
  4:
    id: 301
    meta: 0
    amount: 1
  5:
    id: 302
    meta: 0
    amount: 1
  6:
    id: 303
    meta: 0
    amount: 1
  7:
    id: 304
    meta: 0
    amount: 1
  8:
    id: 305
    meta: 0
    amount: 1
  9:
    id: 306
    meta: 0
    amount: 1
  10:
    id: 307
    meta: 0
    amount: 1
  11:
    id: 308
    meta: 0
    amount: 1
  12:
    id: 309
    meta: 0
    amount: 1
  13:
    id: 311
    meta: 0
    amount: 1
  14:
    id: 314
    meta: 0
    amount: 1
  15:
    id: 315
    meta: 0
    amount: 1
  16:
    id: 316
    meta: 0
    amount: 1
  17:
    id: 317
    meta: 0
    amount: 1
  18:
    id: 267
    meta: 0
    amount: 1
  19:
    id: 268
    meta: 0
    amount: 1
  20:
    id: 272
    meta: 0
    amount: 1
  21:
    id: 283
    meta: 0
    amount: 1
  22:
    id: 271
    meta: 0
    amount: 1
  23:
    id: 275
    meta: 0
    amount: 1
  24:
    id: 258
    meta: 0
    amount: 1
  25:
    id: 261
    meta: 0
    amount: 1
  26:
    id: 262
    meta: 0
    amount: 3
  27:
    id: 260
    meta: 0
    amount: 2
  28:
    id: 297
    meta: 0
    amount: 6
  29:
    id: 322
    meta: 0
    amount: 1
  30:
    id: 332
    meta: 0
    amount: 4